<?php
$sz_chapternames = array(
0 => 
"Inhaltsverzeichnis",
"Historie",
"Weaver-Memorandum",
"Boomphase",
"Alpac-Report",
"Flaute",
"Wiederaufschwung",
"90er Jahre",
"Zukunftsaussichten",
"Probleme der Maschinellen Übersetzung",
"Probleme: Übung 1",
"Probleme: Übung 2",
"Probleme: Übung 3",
"Probleme: Übung 4",
"Probleme: Übung 5",
"Probleme: Übung 6",
"Probleme: Übung 7",
"MÜ: Probleme Übung 8a",
"Probleme: Übung 8b",
"Probleme: Übung 8c",
"Übersetzungsverfahren",
"Übersetzungsverfahren: Übung 1",
"Übersetzungsverfahren: Übung 2",
"Übersetzungsverfahren Übung 3",
"Übersetzungsverfahren: Übung 4",
"Übersetzungsverfahren: Übung 5",
"Übersetzungsverfahren: Übung 6",
"Übersetzungsverfahren: Übung 7",
"Software",
"Software: Übung 1",
"Software: Übung 2",
"Software Übung 3",
"Software: Übung 4",
"Software: Übung 5",
"Evaluierung von MÜ-Systemen",
"Evaluierung: Übung 1",
"Evaluierung: Übung 2",
"Evaluierung: Übung 3",
"Fazit"
);
?>