<?php
    $sz_chapternames = array(
        0 =>
            "Inhaltsverzeichnis",
        "Einordnung des Themas",
        "Wichtige Begriffe",
        "Begriffszusammenhänge",
        "Miniwelt 'Universität'",
        "Grundlagen der Datenmodellierung",
        "Entity-Relationshop-Modell (1/3)",
        "Entity-Relationshop-Modell (2/3)",
        "Entity-Relationshop-Modell (3/3)",
        "Kardinalitäten",
        "Aufgabenbeschreibung Aufgabe 1",
        "Aufgabe 1",
        "Aufgabe 2",
        "Aufgabe 3",
        "Relationales Datenmodell (1/2)",
        "Relationales Datenmodell (2/2)",
        "SQL - Grundlagen (1/2)",
        "SQL - Grundlagen (2/2)",
        "Einsatzbereiche",
        "Beispieltabelle",
        "Datenmanipulation",
        "INSERT",
        "UPDATE",
        "DELETE",
        "Aufgabe 4",
        "Aufgabe 5",
        "Aufgabe 6",
        "Aufgabe 7",
        "Aufgabe 8",
        "Aufgabe 9",
        "Die SELECT-Anweisung (1/2)",
        "Die SELECT-Anweisung (2/2)",
        "Einfache Selektion",
        "Die WHERE-Klausel",
        "SELECT",
        "Aufgabe 10",
        "Aufgabe 11",
        "Aufgabe 12",
        "Anwendung Boolscher Logik (1/2)",
        "Anwendung Boolscher Logik (2/2)",
        "Aufgabe 13",
        "Funktionen in SQL",
        "Aufgabe 14",
        "Anfragen über mehrere Relationen",
        "Aufgabe 15",
        "Aufgabe 16",
        "Aufgabe 17",
        "Aufgabe 18",
        "Ende"
    );
?>